[package]
name = "many"
version = "0.1.0"
edition = "2021"

[dependencies]
stuff.workspace = true
bevy.workspace = true
bevy_rand.workspace = true
bevy_prng.workspace = true
scarlet.workspace = true
clap.workspace = true
